package org.example.test.views.components.datatables.pagging.buttons;

import java.awt.event.ActionEvent;

import org.example.test.views.components.buttons.BasicButton;
import org.example.test.views.components.datatables.AppDataTableListener;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class NextPageButton extends BasicButton {

	/** Value that it is used during deserialization to verify that the sender and receiver of a serialized object have loaded classes for that object that are compatible with respect to serialization. */
	private static final long serialVersionUID = 4112189960223541673L;

	/**
	 * New Instance.
	 */
	public NextPageButton() {
		super("datatable.pagging.button.next.text", "datatable.pagging.button.next.tool.tip");
	}
	
	@Override
	protected void handlerInitializateGUI() {
		super.addActionListener((e) -> nextPageAction(e));
	}

	/**
	 * Send the event generated by pressing the button to the parent component.
	 * 
	 * @param e Event
	 */
	private void nextPageAction(ActionEvent e) {
		log.trace("Next page: {}", e);
		if (super.getParent() instanceof AppDataTableListener) {
			((AppDataTableListener) super.getParent()).nextPageAction(e);
		}
	}
}
