package org.example.test.events;

public enum EventType {
	CLOSE_APPLICATION,
	CLOSE_DIALOG,
	
	OPEN_DIALOG_OPEN_FILE,
	OPEN_DIALOG_SAVE_FILE,
	OPEN_DIALOG_ABOUT,
	OPEN_DIALOG_CONFIGURATION,
	
	ACTION_VIEW_CLEAN_LOG,
	ACTION_VIEW_SAVE_FILE,
	
	ACTION_CONN_CONNECT,
	ACTION_CONN_DISCONNECT,
	ACTION_CONN_SEND_DATA
	
}
