version: '2'
services:
  eurekaserver:
    image: 'ijgomez/course-docker-eureka-server'
    expose:
      - "8761"
    ports:
      - '8761:8761'
  microservice:
    image: 'ijgomez/course-docker-microservice'
    links:
      - eurekaserver
    expose:
      - "8080"
  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - microservice
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'